// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace smartSchool.WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210804184704_tudo")]
    partial class tudo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("smartSchool.WebApi.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sistemas de Informação"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ciência da Computação"
                        });
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreRequisiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Worlkoad")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PreRequisiteId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Name = "Matemática",
                            TeacherId = 1,
                            Worlkoad = 0
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 3,
                            Name = "Matemática",
                            TeacherId = 1,
                            Worlkoad = 0
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Name = "Física",
                            TeacherId = 2,
                            Worlkoad = 0
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            Name = "Português",
                            TeacherId = 3,
                            Worlkoad = 0
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 1,
                            Name = "Inglês",
                            TeacherId = 4,
                            Worlkoad = 0
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            Name = "Inglês",
                            TeacherId = 4,
                            Worlkoad = 0
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 3,
                            Name = "Inglês",
                            TeacherId = 4,
                            Worlkoad = 0
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 1,
                            Name = "Programação",
                            TeacherId = 5,
                            Worlkoad = 0
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 2,
                            Name = "Programação",
                            TeacherId = 5,
                            Worlkoad = 0
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 3,
                            Name = "Programação",
                            TeacherId = 5,
                            Worlkoad = 0
                        });
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BornAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GraduationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Registration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            BornAt = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marta",
                            Phone = "33225555",
                            Registration = 1,
                            RegistrationDate = new DateTime(2021, 8, 4, 15, 47, 3, 629, DateTimeKind.Local).AddTicks(7177),
                            SecondName = "Kent"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            BornAt = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paula",
                            Phone = "3354288",
                            Registration = 2,
                            RegistrationDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(101),
                            SecondName = "Isabela"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            BornAt = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laura",
                            Phone = "55668899",
                            Registration = 3,
                            RegistrationDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(120),
                            SecondName = "Antonia"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            BornAt = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luiza",
                            Phone = "6565659",
                            Registration = 4,
                            RegistrationDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(126),
                            SecondName = "Maria"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            BornAt = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lucas",
                            Phone = "565685415",
                            Registration = 5,
                            RegistrationDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(132),
                            SecondName = "Machado"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            BornAt = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pedro",
                            Phone = "456454545",
                            Registration = 6,
                            RegistrationDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(143),
                            SecondName = "Alvares"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            BornAt = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paulo",
                            Phone = "9874512",
                            Registration = 7,
                            RegistrationDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(149),
                            SecondName = "José"
                        });
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IniDate")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.StudentDiscipline", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IniDate")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("StudentDisciplines");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DisciplineId = 2,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(1655)
                        },
                        new
                        {
                            StudentId = 1,
                            DisciplineId = 4,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2315)
                        },
                        new
                        {
                            StudentId = 1,
                            DisciplineId = 5,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2322)
                        },
                        new
                        {
                            StudentId = 2,
                            DisciplineId = 1,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2324)
                        },
                        new
                        {
                            StudentId = 2,
                            DisciplineId = 2,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2326)
                        },
                        new
                        {
                            StudentId = 2,
                            DisciplineId = 5,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2332)
                        },
                        new
                        {
                            StudentId = 3,
                            DisciplineId = 1,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2334)
                        },
                        new
                        {
                            StudentId = 3,
                            DisciplineId = 2,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2336)
                        },
                        new
                        {
                            StudentId = 3,
                            DisciplineId = 3,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2338)
                        },
                        new
                        {
                            StudentId = 4,
                            DisciplineId = 1,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2341)
                        },
                        new
                        {
                            StudentId = 4,
                            DisciplineId = 4,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2343)
                        },
                        new
                        {
                            StudentId = 4,
                            DisciplineId = 5,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2345)
                        },
                        new
                        {
                            StudentId = 5,
                            DisciplineId = 4,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2346)
                        },
                        new
                        {
                            StudentId = 5,
                            DisciplineId = 5,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2348)
                        },
                        new
                        {
                            StudentId = 6,
                            DisciplineId = 1,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2350)
                        },
                        new
                        {
                            StudentId = 6,
                            DisciplineId = 2,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2352)
                        },
                        new
                        {
                            StudentId = 6,
                            DisciplineId = 3,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2354)
                        },
                        new
                        {
                            StudentId = 6,
                            DisciplineId = 4,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2357)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 1,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2359)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 2,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2361)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 3,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2363)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 4,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2364)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 5,
                            IniDate = new DateTime(2021, 8, 4, 15, 47, 3, 630, DateTimeKind.Local).AddTicks(2366)
                        });
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GraduationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Registration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lauro",
                            Registration = 1,
                            RegistrationDate = new DateTime(2021, 8, 4, 15, 47, 3, 620, DateTimeKind.Local).AddTicks(3460),
                            SecondName = "Oliveira"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Roberto",
                            Registration = 2,
                            RegistrationDate = new DateTime(2021, 8, 4, 15, 47, 3, 624, DateTimeKind.Local).AddTicks(9354),
                            SecondName = "Soares"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ronaldo",
                            Registration = 3,
                            RegistrationDate = new DateTime(2021, 8, 4, 15, 47, 3, 624, DateTimeKind.Local).AddTicks(9377),
                            SecondName = "Marconi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rodrigo",
                            Registration = 4,
                            RegistrationDate = new DateTime(2021, 8, 4, 15, 47, 3, 624, DateTimeKind.Local).AddTicks(9381),
                            SecondName = "Carvalho"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Alexandre",
                            Registration = 5,
                            RegistrationDate = new DateTime(2021, 8, 4, 15, 47, 3, 624, DateTimeKind.Local).AddTicks(9383),
                            SecondName = "Montanha"
                        });
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Discipline", b =>
                {
                    b.HasOne("smartSchool.WebApi.Models.Course", "Course")
                        .WithMany("Disciplines")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartSchool.WebApi.Models.Discipline", "PreRequisite")
                        .WithMany()
                        .HasForeignKey("PreRequisiteId");

                    b.HasOne("smartSchool.WebApi.Models.Teacher", "Teacher")
                        .WithMany("Disciplines")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PreRequisite");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.StudentCourse", b =>
                {
                    b.HasOne("smartSchool.WebApi.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartSchool.WebApi.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.StudentDiscipline", b =>
                {
                    b.HasOne("smartSchool.WebApi.Models.Discipline", "Discipline")
                        .WithMany("StudentsDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartSchool.WebApi.Models.Student", "Student")
                        .WithMany("Disciplines")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Course", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Discipline", b =>
                {
                    b.Navigation("StudentsDisciplines");
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Student", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Teacher", b =>
                {
                    b.Navigation("Disciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
