// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace smartSchool.WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210802232413_secundaria")]
    partial class secundaria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("smartSchool.WebApi.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTeacher")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdTeacher = 1,
                            Name = "Maths"
                        },
                        new
                        {
                            Id = 2,
                            IdTeacher = 2,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            IdTeacher = 3,
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = 4,
                            IdTeacher = 4,
                            Name = "English"
                        },
                        new
                        {
                            Id = 5,
                            IdTeacher = 5,
                            Name = "Programming"
                        });
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Isra",
                            Phone = "33225555",
                            SecondName = "Peres"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ra",
                            Phone = "3354288",
                            SecondName = "Lopes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Samuel",
                            Phone = "55668899",
                            SecondName = "Influentes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Coz",
                            Phone = "6565659",
                            SecondName = "Godz"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Luiza",
                            Phone = "565685415",
                            SecondName = "Ribeiro"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Leo",
                            Phone = "456454545",
                            SecondName = "Lol"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rubens",
                            Phone = "9874512",
                            SecondName = "J"
                        });
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.StudentDiscipline", b =>
                {
                    b.Property<int>("IdStudent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdDiscipline")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdStudent", "IdDiscipline");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentDisciplines");

                    b.HasData(
                        new
                        {
                            IdStudent = 1,
                            IdDiscipline = 2
                        },
                        new
                        {
                            IdStudent = 1,
                            IdDiscipline = 4
                        },
                        new
                        {
                            IdStudent = 1,
                            IdDiscipline = 5
                        },
                        new
                        {
                            IdStudent = 2,
                            IdDiscipline = 1
                        },
                        new
                        {
                            IdStudent = 2,
                            IdDiscipline = 2
                        },
                        new
                        {
                            IdStudent = 2,
                            IdDiscipline = 5
                        },
                        new
                        {
                            IdStudent = 3,
                            IdDiscipline = 1
                        },
                        new
                        {
                            IdStudent = 3,
                            IdDiscipline = 2
                        },
                        new
                        {
                            IdStudent = 3,
                            IdDiscipline = 3
                        },
                        new
                        {
                            IdStudent = 4,
                            IdDiscipline = 1
                        },
                        new
                        {
                            IdStudent = 4,
                            IdDiscipline = 4
                        },
                        new
                        {
                            IdStudent = 4,
                            IdDiscipline = 5
                        },
                        new
                        {
                            IdStudent = 5,
                            IdDiscipline = 4
                        },
                        new
                        {
                            IdStudent = 5,
                            IdDiscipline = 5
                        },
                        new
                        {
                            IdStudent = 6,
                            IdDiscipline = 1
                        },
                        new
                        {
                            IdStudent = 6,
                            IdDiscipline = 2
                        },
                        new
                        {
                            IdStudent = 6,
                            IdDiscipline = 3
                        },
                        new
                        {
                            IdStudent = 6,
                            IdDiscipline = 4
                        },
                        new
                        {
                            IdStudent = 7,
                            IdDiscipline = 1
                        },
                        new
                        {
                            IdStudent = 7,
                            IdDiscipline = 2
                        },
                        new
                        {
                            IdStudent = 7,
                            IdDiscipline = 3
                        },
                        new
                        {
                            IdStudent = 7,
                            IdDiscipline = 4
                        },
                        new
                        {
                            IdStudent = 7,
                            IdDiscipline = 5
                        });
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Claudin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Robertin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clebin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rogerin"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gaulesin"
                        });
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Discipline", b =>
                {
                    b.HasOne("smartSchool.WebApi.Models.Student", null)
                        .WithMany("Disciplines")
                        .HasForeignKey("StudentId");

                    b.HasOne("smartSchool.WebApi.Models.Teacher", "Teacher")
                        .WithMany("Disciplines")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.StudentDiscipline", b =>
                {
                    b.HasOne("smartSchool.WebApi.Models.Discipline", "Discipline")
                        .WithMany("StudentsDisciplines")
                        .HasForeignKey("DisciplineId");

                    b.HasOne("smartSchool.WebApi.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Discipline", b =>
                {
                    b.Navigation("StudentsDisciplines");
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Student", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("smartSchool.WebApi.Models.Teacher", b =>
                {
                    b.Navigation("Disciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
